/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package triangulo;

import java.awt.Color;
import java.lang.Math.*;
import static java.lang.Math.pow;

/**
 *
 * @author santa
 */
public class triangulo extends javax.swing.JFrame {

    /**
     * Creates new form triangulo
     */
    public triangulo() {
        initComponents();
        this.setLocationRelativeTo(this); //centramos nuestra aplicacion al inicio.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrarbtn = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        ppal = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        dib01 = new javax.swing.JLabel();
        inserteladoa = new javax.swing.JLabel();
        inserteladob = new javax.swing.JLabel();
        inserteladoc = new javax.swing.JLabel();
        ladoa = new javax.swing.JTextField();
        ladob = new javax.swing.JTextField();
        ladoc = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        resultadoangulos = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        cerrarbtn.setBackground(new java.awt.Color(220, 255, 255));

        cerrar.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("X");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrar.setPreferredSize(new java.awt.Dimension(30, 30));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout cerrarbtnLayout = new javax.swing.GroupLayout(cerrarbtn);
        cerrarbtn.setLayout(cerrarbtnLayout);
        cerrarbtnLayout.setHorizontalGroup(
            cerrarbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(cerrarbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cerrarbtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        cerrarbtnLayout.setVerticalGroup(
            cerrarbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(cerrarbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cerrarbtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ppal.setBackground(new java.awt.Color(153, 204, 255));
        ppal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ppal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(102, 102, 102));
        titulo.setText("Calcular el area de un triangulo");
        ppal.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 280, 42));

        dib01.setIcon(new javax.swing.ImageIcon("D:\\Pablo\\OneDrive\\Imágenes\\maties_4467c-a77e3.png")); // NOI18N
        ppal.add(dib01, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 310, 250));

        inserteladoa.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        inserteladoa.setForeground(new java.awt.Color(102, 102, 102));
        inserteladoa.setText("Inserte el lado \"a\":");
        ppal.add(inserteladoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 36));

        inserteladob.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        inserteladob.setForeground(new java.awt.Color(102, 102, 102));
        inserteladob.setText("Inserte el lado \"b\":");
        ppal.add(inserteladob, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 36));

        inserteladoc.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        inserteladoc.setForeground(new java.awt.Color(102, 102, 102));
        inserteladoc.setText("Inserte el lado \"c\":");
        ppal.add(inserteladoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 114, 36));

        ladoa.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        ladoa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ladoa.setMinimumSize(new java.awt.Dimension(100, 30));
        ladoa.setPreferredSize(new java.awt.Dimension(100, 30));
        ladoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladoaActionPerformed(evt);
            }
        });
        ppal.add(ladoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 48, 50, 31));

        ladob.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        ladob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ladob.setMinimumSize(new java.awt.Dimension(100, 30));
        ladob.setPreferredSize(new java.awt.Dimension(100, 30));
        ladob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladobActionPerformed(evt);
            }
        });
        ppal.add(ladob, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 88, 50, 31));

        ladoc.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        ladoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ladoc.setMinimumSize(new java.awt.Dimension(100, 30));
        ladoc.setPreferredSize(new java.awt.Dimension(100, 30));
        ladoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladocActionPerformed(evt);
            }
        });
        ppal.add(ladoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 50, 31));

        calcular.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        calcular.setForeground(new java.awt.Color(102, 102, 102));
        calcular.setText("Calcular");
        calcular.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcularMouseClicked(evt);
            }
        });
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        ppal.add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 96, 38));

        resultado.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        resultado.setForeground(new java.awt.Color(51, 51, 51));
        resultado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ppal.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 680, 20));

        resultadoangulos.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        resultadoangulos.setForeground(new java.awt.Color(51, 51, 51));
        resultadoangulos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ppal.add(resultadoangulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 680, 20));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triangulo/Logo.jpg"))); // NOI18N
        ppal.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 290, 100));

        salir.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(102, 102, 102));
        salir.setText("Salir");
        salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
        });
        ppal.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 70, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Pablo\\OneDrive\\Imágenes\\Logos\\logo01.jpg")); // NOI18N
        ppal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 230, 70));

        getContentPane().add(ppal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ladoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ladoaActionPerformed

    private void ladobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ladobActionPerformed

    private void ladocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ladocActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        // TODO add your handling code here: cerrar
        cerrarbtn.setBackground(Color.red);
        cerrar.setForeground(Color.white);
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        // TODO add your handling code here:
        cerrarbtn.setBackground(new Color(220, 255, 255));
        cerrar.setForeground(Color.black);
    }//GEN-LAST:event_cerrarMouseExited

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_calcularActionPerformed

    private void calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularMouseClicked
        // TODO add your handling code here:
        //creamos las varaibles a usar
        String tipo;
        double numa, numb, numc, s, area, numres, angulo, angulo_a, angulo_b, angulo_c;

        //parseamos los valores ingresados
        numa = Integer.parseInt(ladoa.getText());
        numb = Integer.parseInt(ladob.getText());
        numc = Integer.parseInt(ladoc.getText());

        //realizamos las operaciones
        //numres= √( S*(S-A) * (S-B) * (S-C) )
        //S=(A+B+C)/2
        if ((numa + numb) > numc && (numa + numc) > numb && (numb + numc) > numa) {

            s = (numa + numb + numc) / 2;
            area = Math.sqrt((s * (s - numa) * (s - numb) * (s - numc)));

            //determinamos el tipo de angulo
            if (numa == numb && numa == numc && numb == numc) {
                tipo = ("EQUILATERO ");
            } else if (numa == numb || numa == numc || numb == numc) {
                tipo = ("ISÓSCELES");
            } else {
                tipo = ("ESCALENO");
            }
            //operacion matematica para encontrar los angulos.

            angulo_a = (Math.pow(numb, 2) + Math.pow(numc, 2) - Math.pow(numa, 2)) / (2 * numb * numc);
            angulo_b = (Math.pow(numa, 2) + Math.pow(numc, 2) - Math.pow(numb, 2)) / (2 * numa * numc);
            angulo_c = (Math.pow(numa, 2) + Math.pow(numb, 2) - Math.pow(numc, 2)) / (2 * numa * numb);

            resultado.setText(("El area del triangulo solicitado es: " +  Math.round (area)) + ("  y el tipo de triangulo es: " + tipo));
            resultadoangulos.setText(("El angulo A es: " + Math.round(Math.toDegrees(Math.acos(angulo_a)))) + (", el angulo B es: " + Math.round(Math.toDegrees(Math.acos(angulo_b))))
                    + (" y el angulo C es: " + Math.round(Math.toDegrees(Math.acos(angulo_c)))));
            ladoa.setText(""); //se limpia los jtext apenas se realizan los calulos
            ladob.setText(""); //se limpia los jtext apenas se realizan los calulos
            ladoc.setText(""); //se limpia los jtext apenas se realizan los calulos
        }

    }//GEN-LAST:event_calcularMouseClicked

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);//boton para salir de la aplicacion.
    }//GEN-LAST:event_salirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new triangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JLabel cerrar;
    private javax.swing.JPanel cerrarbtn;
    private javax.swing.JLabel dib01;
    private javax.swing.JLabel inserteladoa;
    private javax.swing.JLabel inserteladob;
    private javax.swing.JLabel inserteladoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField ladoa;
    private javax.swing.JTextField ladob;
    private javax.swing.JTextField ladoc;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel ppal;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel resultadoangulos;
    private javax.swing.JButton salir;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
